### ISSUE TITLE
how to launch ORDB node

### ISSUE THREAD

**Issue by phoenixxz** [Ayms/node-Tor#20]
Can anyone tell me how to launch ORDB node ?

**Comment by Ayms** [comment]
To launch the OR or ORDB, do:

``node node-tor.js OR_name OR_IP OR_port OR_wsport OR_fingerprint OR_version``

Example: ``node node-tor.js ordb2 37.59.47.27 9062 9063 55C920B34C946B7A88DEE1165A0A1834CD6BCE66 1.0.0``

OR_name is where you have created the keys for this OR, see https://github.com/Ayms/node-Tor#create-your-keys-and-publish-your-node

You get the fingerprint as a result of the call to ``publish.js``

If you don't want to publish your node then just comment all the calls to publish in https://github.com/Ayms/node-Tor/blob/master/lib/publish.js#L71 and just call ``publish`` with a fake IP to get the fingerprint

The ORDB port is the OR_port (OR_wsport is the port to connect via WebSockets), then to set the ORDB node inside browsers you must put the right parameters in https://github.com/Ayms/node-Tor/blob/master/lib/node-tor.js#L203

And the same for one_OR (https://github.com/Ayms/node-Tor/blob/master/lib/node-tor.js#L200), which is by default the node the browser is connecting to via WebSockets

And modulus is the public part of the RSA key

To get it, do:

``openssl rsa -pubin -inform PEM -text -noout < pub-key.pem``

If needed ``pub-key.pem`` can be retrieved doing ``openssl rsa -in priv-key.pem -pubout``

modulus is not set for one_OR since CREATE_FAST is used currently from the browser and does not need the RSA key

Indeed, probably this deserves to be documented a bit better, then this issue will act as such

**Comment by phoenixxz** [comment]
node node-tor.js ordb2 37.59.47.27 9062 9063 55C920B34C946B7A88DEE1165A0A1834CD6BCE66 1.0.0
when I run this , there are errors:
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module '/root/node-Tor/lib/dirs.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/node-Tor/lib/node-tor.js:116:33)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

**Comment by Ayms** [comment]
Indeed... I have added dirs.js which is a file just containing ``exports.Dirs=[""];`` and is in fact not used, to remove for a next update

**Comment by phoenixxz** [comment]
Thanks very much. What is ORDB?

**Comment by phoenixxz** [comment]
Thanks! I just want to set up the environment and download a picture from the browser using node-tor circuit. But It does not work now. I can't input anything from the browser. 

Is "update the routers" necessary for setting up the environment?

**Comment by Ayms** [comment]
Strange, I don't see the comment I received by email

Yes you must update the routers as described here: https://github.com/Ayms/node-Tor#update-the-routers

This will generate guards.js and exit.js

Then you must xhr from the browser those two files from the server used to load the code, see https://github.com/Ayms/node-Tor/blob/master/lib/src/browser2.js#L1102, you can replace guards and exit by the correct url, another TODO to make this generic, currently node-Tor is designed to work with the Peersm demo
